version: "3"

services:
  app:
    build:
#      context: app
      args:
        - edition=team
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=${MM_USERNAME:-mattermost}
      - MM_PASSWORD=${MM_PASSWORD:-changemeReally!23453}
      - MM_DBNAME=${MM_DBNAME:-mattermost}
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME:-mattermost}:${MM_PASSWORD:-changemeReally!23453}@db2:5432/${MM_DBNAME:-mattermost}?sslmode=disable&connect_timeout=10
    ports:
      - "80:8000"
#  db3:
#    image: mariadb
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-someDefaultPass}
#      - MYSQL_DATABASE=${MM_DBNAME:-mattermost}
#      - MYSQL_USER=${MM_USERNAME:-mattermost}
#      - MYSQL_PASSWORD=${MM_PASSWORD:-changemeReally!23453}
#    volumes:
#      - ./volumes/db3/mysqldata:/var/lib/mysql
  db2:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${MM_DBNAME:-mattermost}
      - POSTGRES_USER=${MM_USERNAME:-mattermost}
      - POSTGRES_PASSWORD=${MM_PASSWORD:-changemeReally!23453}
      #- PGDATA=/var/lib/postgresql/data/main
    #volumes:
      #- /Users/petr/dev/edmstudio.com/volatile/edmtrail/docker-postgres-data:/var/lib/postgresql/data
      #- ${POSTGRES_DATA_DIR:?Specify a PostgreSQL data dir location}:/var/lib/postgresql/data
    #  - trail-postgres-vol-1:/var/lib/postgresql/data
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  db:
     restart: "no"
     image: alpine:latest
     command: tail -f /dev/null
     #entrypoint: "true"
     tty: true

  web:
     restart: "no"
     image: alpine:latest
     command: tail -f /dev/null
     #entrypoint: "true"
     tty: true

#  webapp-builder:
#    build:
#      context: webapp-builder
#    restart: "no"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
